// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Connected() {
  return window['go']['main']['App']['Connected']();
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Modes() {
  return window['go']['main']['App']['Modes']();
}

export function OpenFileBrowser(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileBrowser'](arg1, arg2, arg3);
}

export function Pair(arg1) {
  return window['go']['main']['App']['Pair'](arg1);
}

export function RefreshDevices() {
  return window['go']['main']['App']['RefreshDevices']();
}

export function SendTransaction(arg1) {
  return window['go']['main']['App']['SendTransaction'](arg1);
}

export function Unpair(arg1) {
  return window['go']['main']['App']['Unpair'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
