// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {edc} from '../models';
import {ecr} from '../models';
import {main} from '../models';

export function Config():Promise<config.Config>;

export function Connect():Promise<void>;

export function Connected():Promise<boolean>;

export function Devices():Promise<Array<edc.Device>>;

export function Disconnect():Promise<void>;

export function Modes():Promise<Array<ecr.Mode>>;

export function OpenFileBrowser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Pair(arg1:main.PairRequest):Promise<void>;

export function RefreshDevices():Promise<void>;

export function SendTransaction(arg1:main.SendTransactionRequest):Promise<void>;

export function Unpair(arg1:main.UnpairRequest):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
